import os
import signal
os.system("pkill -f 'aiogram'")   # eski bot jarayonlarini o‘ldiradi
# PEDAGOGIKA BOTI — 100 TA SAVOL — 100% ISHLAYDI (YANGI VERSIYA)
!pip install aiogram nest-asyncio -q

import json
import nest_asyncio
nest_asyncio.apply()

from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup, CallbackQuery
from aiogram import F
import asyncio
import random

# TO'LIQ 100 TA SAVOL (87-100 gacha ham to'g'ri)
questions_data = [
    {"mavzu": "Pedagogika", "savol": "Asosiy dars tiplari. O‘qituvchining darsga tayyorlanish tizimi.", "javob": "Dars tiplari: yangi bilim beruvchi, bilim va ko‘nikmalarni mustahkamlovchi, takrorlovchi, nazorat–baholovchi, aralash darslar. O‘qituvchi darsga tayyorlanishda: o‘quv dasturini o‘rganadi, maqsad va vazifalarni aniqlaydi, metod va vositalarni tanlaydi, dars konspektini tuzadi, texnik vositalarni tayyorlaydi, baholash mezonlarini belgilaydi."},
    {"mavzu": "Pedagogika", "savol": "Davlat ta’lim standartlari. Ta’lim mazmunini qurish va tanlash me’yorlari.", "javob": "Davlat ta’lim standartlari (DTS) — ta’lim sifati, mazmuni va natijalariga qo‘yilgan majburiy talablar majmui. Mazmunni tanlash me’yorlari: ilmiylik, tizimlilik, izchillik, yosh va psixologik xususiyatlarga moslik, milliy va umuminsoniy qadriyatlar bilan uyg‘unlik, amaliy ahamiyat."},
    {"mavzu": "Pedagogika", "savol": "Dars va uning xususiyatlari.", "javob": "Dars — o‘quv jarayonining asosiy tashkiliy shakli bo‘lib, o‘quvchilarni maqsadli, tizimli o‘qitishni ta’minlaydi. Xususiyatlari: maqsadga yo‘naltirilganlik, rejalilik, o‘quvchi faolligi, teskari aloqa mavjudligi, vaqt chegaralanganligi, natijadorlik."},
    {"mavzu": "Pedagogika", "savol": "Darsning psixologik-pedagogik tahlili, o‘quvchi shaxsi va guruh jamoasi.", "javob": "Psixologik-pedagogik tahlil — dars jarayonida o‘quvchilarning bilim olish motivatsiyasi, diqqat, tafakkur, emotsional holati va o‘qituvchi bilan o‘zaro muloqotini baholashdir. O‘quvchi shaxsi — individual psixik xususiyatlar majmui; guruh jamoasi — ijtimoiy faollik, hamkorlik, o‘zaro yordam va o‘qishdagi birlashganlik darajasini ifodalaydi."},
    {"mavzu": "Pedagogika", "savol": "Dasturiy pedagogik vositalar.", "javob": "Dasturiy pedagogik vositalar — o‘qitish jarayonida kompyuter, multimedia, elektron darslik, ta’lim platformalari, simulyator va test tizimlari yordamida o‘qitishni avtomatlashtiruvchi vositalar. Ular interfaol, nazoratli va individual o‘qitish imkonini beradi."},
    {"mavzu": "Pedagogika", "savol": "Yosh psixologiyasi. O‘quvchilarga individual yondoshish psixologiyasi.", "javob": "Yosh psixologiyasi — insonning yosh davrlari bo‘yicha psixik rivojlanish qonuniyatlarini o‘rganadi. Individual yondashuv — har bir o‘quvchining qobiliyati, temperament, o‘rganish uslubi, motivatsiyasiga mos o‘qitish metodini tanlashni bildiradi."},
    {"mavzu": "Pedagogika", "savol": "Ijodiy tajriba faoliyati. Ta’limni insonparvarlashtirish va ijtimoiylashtirish. Ta’lim mazmunining milliylik va baynalmilallik jihatlari.", "javob": "Ijodiy tajriba — o‘qituvchi va o‘quvchilarning yangi pedagogik yondashuvlarni sinab ko‘rish faoliyati. Insonparvarlashtirish — ta’limda shaxsni markazga qo‘yish, unga hurmat bilan yondashish. Ijtimoiylashtirish — o‘quvchini jamiyatga moslashtirish jarayoni. Milliylik — o‘z xalqining qadriyatlari va madaniyatiga tayangan ta’lim; baynalmilallik — jahon ilmiy yutuqlari va tajribasini uyg‘unlashtirish."},
    {"mavzu": "Pedagogika", "savol": "Ilmiy dunyoqarashni shakllantirish, estetik va ma’naviy tarbiya.", "javob": "Ilmiy dunyoqarash — tabiat, jamiyat va tafakkurni ilmiy asosda tushuntirish qobiliyati. Estetik tarbiya — go‘zallikni anglash, san’atni qadrlash, estetik didni rivojlantirish. Ma’naviy tarbiya — insonda axloqiy qadriyatlar, vijdon, halollik, mas’uliyat tuyg‘ularini shakllantirish."},
    {"mavzu": "Pedagogika", "savol": "Laboratoriya va amaliy, seminar mashg‘ulotlarning mazmuni, tuzilishi va ularni o‘tkazish metodikasi.", "javob": "Laboratoriya mashg‘ulotlari — tajriba va amaliy ishlar orqali nazariy bilimlarni mustahkamlash. Seminar mashg‘uloti — o‘quvchilarning mustaqil fikrlash, tahlil qilish va muhokama qilish ko‘nikmalarini rivojlantiradi. Metodika: tayyorgarlik → topshiriq berish → bajarish → natijalarni tahlil qilish → xulosalash."},
    {"mavzu": "Pedagogika", "savol": "Maktab va o‘rta maxsus ta’lim fan kursining mantiqiy-didaktik tahlili.", "javob": "Mantiqiy-didaktik tahlil — fan kursining mazmunini maqsad, vazifa, tushuncha tizimi, mantiqiy bog‘lanish va o‘qitish ketma-ketligi nuqtai nazaridan tahlil qilish. Bu tahlil o‘quv materialini bosqichma-bosqich, osondan qiyinga o‘tish tamoyiliga asoslangan holda tashkil etish imkonini beradi."},
    {"mavzu": "Pedagogika", "savol": "Maktab va o‘rta maxsus ta’lim muassasalari informatika kursining mazmuni.", "javob": "Informatika kursi mazmuni: axborot tushunchasi, kompyuter arxitekturasi, dasturlash asoslari, algoritmlar, ma’lumotlar bazasi, tarmoqlar, axborot xavfsizligi, sun’iy intellekt elementlari va axborot madaniyati. Maqsad — o‘quvchilarda axborot texnologiyalaridan samarali foydalanish ko‘nikmasini shakllantirish."},
    {"mavzu": "Pedagogika", "savol": "Maktab va o‘rta maxsus ta’lim informatika fani kursining rivojlantirishning asosiy yo‘nalishlari.", "javob": "Asosiy yo‘nalishlar: raqamli savodxonlikni oshirish; algoritmik va mantiqiy tafakkurni rivojlantirish; dasturlash ko‘nikmalarini bosqichma-bosqich o‘rgatish; STEAM ta’lim integratsiyasi; masofaviy o‘qitish texnologiyalaridan foydalanish; kiberxavfsizlik va media madaniyatni rivojlantirish."},
    {"mavzu": "Pedagogika", "savol": "Maktabda, akademik litsey va kasb-hunar kollejlarida, oliy ta’lim va oliy ta’limdan tashqari, darsdan va sinfdan tashqari informatika fani ta’limining maqsadlari.", "javob": "Maktabda: axborot madaniyati va kompyuter savodxonligini shakllantirish. Litsey va kollejda: kasbiy yo‘nalishdagi dasturlash va AKT ko‘nikmalarini chuqurlashtirish. Oliy ta’limda: ilmiy, texnik va tahliliy fikrlash asosida AKTni ijodiy qo‘llash. Oliy ta’limdan tashqarida: hayot davomida o‘qish va qayta tayyorlash. Darsdan tashqari: musobaqa, olimpiada, IT-klublar orqali qiziqishni rivojlantirish."},
    {"mavzu": "Pedagogika", "savol": "Mantiqiy va obrazli tafakkurni rivojlantirish, fazoviy tasavvurlarni rivojlantirish.", "javob": "Mantiqiy tafakkur — analiz, sintez, umumlashtirish, sabab–natija bog‘lanishlarini aniqlash qobiliyatidir. Obrazli tafakkur — tasavvur orqali fikrlash, vizual shakllarda o‘ylash. Fazoviy tasavvur — ob’ektlarning joylashuvi va shaklini ongda tasavvur etish. Bu ko‘nikmalarni rivojlantirish uchun chizmalar, modellashtirish, algoritmik topshiriqlar, dasturlash va robototexnika mashg‘ulotlari samarali."},
    {"mavzu": "Pedagogika", "savol": "Matematik-statistik metodlardan foydalanib olingan ma’lumotlarni qayta ishlash va tahlil qilish.", "javob": "Statistik metodlar — o‘rta qiymat, dispersiya, korrelyatsiya, regressiya, variatsiya tahlili kabi usullar orqali ma’lumotlarni tizimlashtirish, tahlil qilish va xulosalashdir. Bu metodlar pedagogik tajriba, sotsiologik so‘rov yoki test natijalarini ilmiy asosda tahlil qilishda qo‘llanadi."},
    {"mavzu": "Pedagogika", "savol": "Metodikaning asosiy prinsiplari.", "javob": "Ilmiylik – bilimlar ilmiy asosda berilishi. Tizimlilik va izchillik – mavzularning mantiqiy ketma-ketligi. Faollik va ongli ishtirok – o‘quvchi faol o‘rganadi. Nazariya va amaliyot birligi. Ko‘rgazmalilik. Individual yondashuv va differensiallashtirish."},
    {"mavzu": "Pedagogika", "savol": "Metodikaning xususiy prinsiplari.", "javob": "Bu prinsiplarga o‘qitilayotgan fanga xos didaktik talablar kiradi. Masalan, informatika metodikasida: algoritmik tafakkurni rivojlantirish; texnik vositalardan oqilona foydalanish; amaliy mashg‘ulotlarni ustun qo‘yish; xavfsizlik qoidalariga rioya qilish; o‘quvchilarni muammoli vaziyatlar orqali fikrlashga o‘rgatish."},
    {"mavzu": "Pedagogika", "savol": "Moddiy va ma’naviy madaniyat elementlari va predmetlari ta’lim vositasi sifatida.", "javob": "Moddiy madaniyat vositalari: texnika, maket, modellar, ko‘rgazmali qurollar. Ma’naviy madaniyat elementlari: san’at, adabiyot, urf-odat, xalq og‘zaki ijodi. Ular ta’lim vositasi sifatida o‘quvchilarda estetik did, vatanparvarlik, tarixiy xotira va ijodkorlikni rivojlantirishga xizmat qiladi."},
    {"mavzu": "Pedagogika", "savol": "Mualliflik maktablari.", "javob": "Mualliflik maktablari — ilg‘or pedagoglarning o‘z pedagogik konsepsiyasi asosida tashkil etilgan o‘quv-tarbiya tizimlari. Masalan: Sh. Amonov, V. Shatalov, S. Lysenkova, M. Montessori, L. Zankov, V. Davыdov maktablari. Ularning xususiyati — innovatsion metodika, o‘quvchiga individual yondashuv, ijodiy rivojlanishga urg‘u."},
    {"mavzu": "Pedagogika", "savol": "Mustaqil ta’lim (eksternat); kunduzgi, sirtqi, masofaviy va boshqalar.", "javob": "Mustaqil ta’lim (eksternat): o‘quvchi o‘qituvchisiz o‘zi o‘rganadi va yakuniy nazoratdan o‘tadi. Kunduzgi ta’lim: to‘liq auditoriya mashg‘ulotlariga asoslanadi. Sirtqi ta’lim: o‘quvchi mustaqil o‘rganib, sessiyada topshiriq topshiradi. Masofaviy ta’lim: internet texnologiyalar orqali o‘qitish. Barchasining maqsadi — ta’limga keng imkoniyat yaratish va “uzluksiz ta’lim” tamoyilini ro‘yobga chiqarish."},
    {"mavzu": "Pedagogika", "savol": "Pedagogik mahoratning komponentlari.", "javob": "Pedagogik mahorat — o‘qituvchining o‘quv-tarbiya jarayonini samarali tashkil etish qobiliyatidir. Asosiy komponentlari: Kasbiy bilimlar tizimi (pedagogika, psixologiya, metodika); Pedagogik texnika (nutq, mimika, boshqaruv usullari); Kommunikativ mahorat; Ijodkorlik va refleksiya; Shaxsiy fazilatlar (mehribonlik, talabchanlik, sabr)."},
    {"mavzu": "Pedagogika", "savol": "Pedagogik tajribalarni o‘tkazish.", "javob": "Pedagogik tajriba — ta’lim-tarbiya jarayonidagi yangilikni ilmiy asosda sinovdan o‘tkazish. Maqsad — yangi metod yoki texnologiyaning samaradorligini aniqlash. Jarayon: muammo tanlash → gipoteza ilgari surish → tajriba guruhlarini ajratish → natijalarni tahlil qilish → xulosa chiqarish."},
    {"mavzu": "Pedagogika", "savol": "Pedagogik tajribani o‘tkazishning asosiy bosqichlari.", "javob": "Tasdiqlovchi bosqich – mavjud holatni aniqlash, diagnostika. Shakllantiruvchi bosqich – yangi metod yoki texnologiyani joriy etish. Ta’limiy bosqich – o‘quv jarayonida amaliy qo‘llash. Umumlashtiruvchi bosqich – tajriba natijalarini tahlil qilish, ilmiy xulosalar chiqarish."},
    {"mavzu": "Pedagogika", "savol": "Pedagogik texnologiyalarning asosiy turlari.", "javob": "An’anaviy texnologiya – o‘qituvchi markazli ta’lim. Muammoli o‘qitish texnologiyasi. Modulli texnologiya. Rivojlantiruvchi o‘qitish texnologiyasi. Axborot-kommunikatsion texnologiyalar. Kollektiv va hamkorlikda o‘qitish texnologiyasi. O‘yinli va interfaol texnologiyalar."},
    {"mavzu": "Pedagogika", "savol": "Reproduktiv va muammoli–izlanuvchan o‘qitish metodlari.", "javob": "Reproduktiv metod – tayyor bilimni o‘zlashtirish, ko‘rsatmaga amal qilish (takrorlash, mashq, nazorat). Muammoli–izlanuvchan metod – o‘quvchini mustaqil fikrlashga, muammoni yechishga yo‘naltiradi. Farqi: birinchisida tayyor bilim beriladi, ikkinchisida bilimni o‘quvchi o‘zi kashf etadi."},
    {"mavzu": "Pedagogika", "savol": "Rivojlangan xorijiy mamlakatlarda fan va kasb tanlashga yo‘llash ishlarining mazmuni.", "javob": "AQSH, Yaponiya, Germaniya, Janubiy Koreya tajribasida kasbga yo‘naltirish: maktabdan boshlab “career guidance” darslari o‘tiladi; testlar, psixologik diagnostika, kasb yarmarkalari o‘tkaziladi; ishlab chiqarish bilan hamkorlikda amaliyotlar yo‘lga qo‘yilgan; kasb tanlashda o‘quvchining qiziqishi va qobiliyati asosiy mezon. Bu tizimning asosiy g‘oyasi – inson kapitalini rivojlantirish."},
    {"mavzu": "Pedagogika", "savol": "Rivojlantiruvchi, o‘quvchi shaxsiga yo‘naltirilgan, modulli, muammoli, didaktik o‘yinli, kontekstli, axborotli, tabaqalashtirilgan, multimediyali, o‘z-o‘zini rivojlantiruvchi texnologiyalar.", "javob": "Rivojlantiruvchi – tafakkur va ijodkorlikni faollashtiradi. Shaxsga yo‘naltirilgan – o‘quvchining ehtiyojiga moslashgan. Modulli – mavzular mustaqil o‘quv bloklariga bo‘linadi. Muammoli – muammoli savollar orqali o‘rganish. Didaktik o‘yinli – o‘yin orqali o‘rganish. Kontekstli – real hayot vaziyatlariga asoslanadi. Axborotli va multimediyali – AKT, video, simulyatorlardan foydalanish. Tabaqalashtirilgan – o‘quvchilar imkoniyatiga qarab darajalarga bo‘linadi. O‘z-o‘zini rivojlantiruvchi – refleksiya va o‘zini baholashni rivojlantiradi."},
    {"mavzu": "Pedagogika", "savol": "Sinf-dars tizimi.", "javob": "Sinf-dars tizimi — Y.A. Komenskiy tomonidan ishlab chiqilgan ta’limni tashkil etish shakli. Asosiy belgilar: sinflar yosh va tayyorgarlikka ko‘ra bo‘linadi; o‘quv yili va dars jadvali mavjud; dars maqsadi, tuzilishi, vaqti belgilangan; o‘qituvchi rahbar, o‘quvchilar jamoa tarzida o‘rganadi."},
    {"mavzu": "Pedagogika", "savol": "Tabiat, jamiyat, inson, texnologiya va faoliyat usullari haqidagi bilimlar sistemasi.", "javob": "Bu — fanlararo yondashuv tamoyiliga asoslangan bilimlar tizimi bo‘lib, quyidagilarni o‘z ichiga oladi: Tabiat – biologiya, ekologiya, fizika, kimyo asoslari; Jamiyat – tarix, huquq, iqtisod; Inson – psixologiya, madaniyat, etika; Texnologiya – ishlab chiqarish va AKT yutuqlari; Faoliyat usullari – tahlil, modellashtirish, muloqot, boshqaruv. Bular o‘quvchilarda dunyoqarash birligini shakllantiradi."},
    {"mavzu": "Pedagogika", "savol": "Tashxislovchi, ogohlantiruvchi, joriy, oraliq va yakuniy nazorat turlari. Og‘zaki, yozma va kompyuterli nazorat turlari.", "javob": "Tashxislovchi nazorat – o‘quvchilarning dastlabki bilim darajasini aniqlash. Ogohlantiruvchi – xatolarni erta aniqlash va tuzatish. Joriy nazorat – mavzu davomida o‘quvchi faoliyatini baholash. Oraliq nazorat – bo‘lim yoki semestr yakunida. Yakuniy nazorat – butun kurs natijalarini baholash. Shakllari: Og‘zaki – suhbat, savol-javob; Yozma – test, diktant, insho; Kompyuterli – onlayn test, avtomatik baholash tizimi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim va shaxs. Ta’lim va jamiyat, ta’lim, fan va madaniyat.", "javob": "Ta’lim — shaxsni har tomonlama rivojlantirishga xizmat qiluvchi ijtimoiy jarayon. Ta’lim va shaxs: ta’lim shaxsning bilim, ko‘nikma, qadriyat va dunyoqarashini shakllantiradi. Ta’lim va jamiyat: ta’lim jamiyat taraqqiyotining asosiy omilidir. Ta’lim, fan va madaniyat: ular o‘zaro uzviy bog‘liq — fan ilmiy asosni, madaniyat esa ma’naviy mazmunni beradi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim vositalari.", "javob": "Ta’lim vositalari — bilim, ko‘nikma va malakalarni shakllantirish uchun qo‘llaniladigan barcha moddiy va axborot resurslaridir. Turlari: Didaktik vositalar (kitob, jadval, kartochka); Texnik vositalar (kompyuter, proyektor, audio-video); Axborot texnologiyalari (multimedia, onlayn platformalar); Ko‘rgazmali vositalar (modellar, maketlar, namoyishlar)."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim vositalarning ko‘pxilligi va uni tizimlashtirish.", "javob": "Ko‘p xil vositalar — mazmun, shakl va texnik imkoniyatiga ko‘ra turlicha bo‘ladi. Tizimlashtirish mezonlari: Axborot manbai bo‘yicha: og‘zaki, bosma, texnik. Ta’sir shakli bo‘yicha: ko‘rish, eshitish, amaliy. O‘quv bosqichi bo‘yicha: boshlang‘ich, o‘rta, oliy. Vazifasiga ko‘ra: o‘rgatuvchi, nazorat qiluvchi, rivojlantiruvchi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim jarayonida o‘zaro muomala va dialogni amalga oshirish muammolari. Kasbiy pedagogik faoliyatining mohiyati.", "javob": "Muomala va dialog muammolari — o‘qituvchi va o‘quvchi o‘rtasida muloqot madaniyatining yetishmasligi, biryoqlama axborot uzatish, o‘quvchi faolligining pastligi bilan bog‘liq. Kasbiy pedagogik faoliyat mohiyati — o‘qituvchining bilim berish, tarbiyalash, rivojlantirish va boshqarish vazifalarini ijodkorlik bilan bajarish jarayoni."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim jarayonini tashkil etish modellari.", "javob": "An’anaviy model – o‘qituvchi markazda, ma’lumot beruvchi rolida. Shaxsga yo‘naltirilgan model – o‘quvchi markazda, mustaqil faoliyatga tayanadi. Hamkorlikdagi ta’lim modeli – o‘qituvchi va o‘quvchi o‘zaro hamkorlikda o‘rganadi. Axborotli-ta’lim modeli – AKT asosida o‘qitish. Kompetensiyaga yo‘naltirilgan model – amaliy natijaga asoslangan ta’lim."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim jarayonining mohiyati, harakatlantiruvchi kuchlari, qarama-qarshiliklari va mantiqiy tuzilmasi.", "javob": "Ta’lim jarayoni — o‘qituvchi va o‘quvchi o‘rtasidagi ikki tomonlama faoliyat. Harakatlantiruvchi kuchlar — qarama-qarshiliklar: yangi bilimga ehtiyoj va mavjud bilimlar o‘rtasidagi farq; nazariya va amaliyot o‘rtasidagi tafovut. Mantiqiy tuzilma: motivatsiya → maqsad → mazmun → metod → natija → teskari aloqa."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim ijtimoiy madaniyat fenomeni sifatida.", "javob": "Ta’lim — jamiyat madaniyatini uzatish, saqlash va rivojlantirish vositasi. U nafaqat bilim berish, balki madaniy qadriyatlarni, urf-odat va axloqiy me’yorlarni avloddan-avlodga o‘tkazish jarayonidir. Shuning uchun ta’lim — ijtimoiy madaniyatning asosiy instituti hisoblanadi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim qonuniyatlari va tamoyillari. Asosiy didaktik nazariyalar: turli ta’lim sistemalarida shaxsni rivojlantirish nazariyalari.", "javob": "Qonuniyatlar: maqsad, mazmun, metod, shakl va natija o‘rtasidagi bog‘liqlik. Tamoyillar: ilmiylik, tizimlilik, ongli faollik, izchillik, mustaqillik, nazariya va amaliyot birligi. Asosiy nazariyalar: P. Galperin – bosqichli o‘qitish nazariyasi; L. Vygotskiy – yaqin rivojlanish zonasi nazariyasi; L. Zankov – rivojlantiruvchi ta’lim; J. Piaget – kognitiv rivojlanish bosqichlari."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim mazmuni va uning ilmiy asoslari.", "javob": "Ta’lim mazmuni — o‘quvchilarga beriladigan bilim, ko‘nikma, malaka va qadriyatlar tizimi. Ilmiy asoslari: pedagogika va psixologiya qonuniyatlari; fan yutuqlari va ilmiy yangiliklar; shaxsni har tomonlama rivojlantirish tamoyillari. Mazmun — jamiyat ehtiyoji va shaxs qobiliyatlari uyg‘unligida belgilanadi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim mazmunini me’yorlovchi normativ hujjatlar. Ta’lim texnologiyalari va o‘qitish metodlari.", "javob": "Normativ hujjatlar: “Ta’lim to‘g‘risida” Qonun; O‘zbekiston Respublikasi DTS; O‘quv rejalari va dasturlari; Me’yoriy-metodik yo‘riqnomalar. Ta’lim texnologiyalari — dars jarayonini ilmiy asosda loyihalash va tashkil etish usullari. O‘qitish metodlari: tushuntirish, suhbat, ko‘rgazmali, amaliy, muammoli, interfaol va tadqiqot metodlari."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim mazmunini didaktik vositalar orqali modellashtirish.", "javob": "Didaktik modellashtirish — o‘quv jarayonini nazariy model sifatida ifodalash. Ma’no: o‘quv materialini tizimli, bosqichma-bosqich taqdim etish. Vositalar: darslik, sxema, diagramma, multimedia, interfaol taxta. Model vazifalari: ta’lim maqsadini aniqlash, mazmunni strukturaga solish, natijani oldindan ko‘rish."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim maqsadlari va taksonomiyalari, rivojlantiruvchi ta’lim nazariyasi; o‘quv faoliyati nazariyasi va uning sub’ekti; mazmunli umumlashtirish nazariyasi; aqliy harakatlarni bosqichma-bosqich shakllantirish nazariyasi.", "javob": "Ta’lim maqsadi – shaxsning bilim, ko‘nikma va malakasini shakllantirish yo‘nalishi. Taksonomiya (B. Bloom) – maqsadlarni bosqichma-bosqich ifodalash: bilish → tushunish → qo‘llash → tahlil → sintez → baholash. Rivojlantiruvchi ta’lim (L. Zankov, Vygotskiy) – o‘quvchi fikrlashini, mustaqilligini rivojlantiradi. O‘quv faoliyati nazariyasi (Leontyev) – o‘quvchi faoliyatining sub’ekti sifatida faol ishtirok etadi. Mazmunli umumlashtirish (Davydov) – o‘quv materialining mohiyatini umumiy g‘oyalar orqali o‘zlashtirish. Aqliy harakatlarni bosqichma-bosqich shakllantirish (Galperin) – harakatlar: motiv → yo‘naltirish → tashqi → ichki → avtomatlashtirish."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim muassasalarining tiplari.", "javob": "Ta’lim tizimi turli tipdagi muassasalardan iborat: Maktabgacha ta’lim muassasalari; Umumta’lim maktablari (boshlang‘ich, o‘rta, yuqori bosqich); Kasb-hunar ta’limi muassasalari (kollej, texnikum); Oliy ta’lim muassasalari (universitet, institut, akademiya); Qo‘shimcha ta’lim markazlari (kurslar, malaka oshirish); Masofaviy va onlayn ta’lim markazlari."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim nazariyasi va metodlari. Metod haqida tushuncha va uning tasnifi.", "javob": "Ta’lim nazariyasi — o‘qitish jarayonining qonuniyatlarini o‘rganuvchi pedagogika sohasi. Metod — o‘qituvchi va o‘quvchi faoliyatini tashkil etish yo‘li. Tasnifi: Bilim manbai bo‘yicha: og‘zaki, ko‘rgazmali, amaliy; Faollik darajasiga ko‘ra: reproduktiv, muammoli, tadqiqotli; Maqsadiga ko‘ra: o‘rgatuvchi, rivojlantiruvchi, nazorat qiluvchi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim olish jarayonining psixologik mohiyati va tuzilishi. O‘zlashtirish jarayonining psixologiyasi.", "javob": "Ta’lim — shaxsning idrok, xotira, tafakkur, e’tibor kabi psixik jarayonlari bilan uzviy bog‘liq. O‘zlashtirish jarayoni bosqichlari: Idrok etish; Tushunish; Mustahkamlash; Qo‘llash; Refleksiya. Bu jarayon motivatsiya va ijobiy psixologik muhit bilan mustahkamlanadi."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim texnologiyalari oldindan qo‘yilgan tashxislanuvchi aniq maqsadlar va etalon asosida ta’lim jarayoni oldindan loyihalashtirish va kutilayotgan natijani kafolotlovchi tartiblangan, tizimlashtirilgan hatti-harakatlar, amallar va muammolar majmuasi sifatida.", "javob": "Bu ta’rif zamonaviy pedagogik texnologiya mohiyatini anglatadi. Ya’ni — o‘qitish jarayonini oldindan loyihalash, aniq maqsad qo‘yish, o‘lchovli natijaga erishishni kafolatlaydigan tizimdir. Xususiyatlari: Tizimlilik, Natijaga yo‘naltirilganlik, Bosqichma-bosqichlik, Teskari aloqa asosida boshqarish."},
    {"mavzu": "Pedagogika", "savol": "Ta’lim umuminsoniy ijtimoiy tajribani egallash vositasi. Bilish nazariyasi ta’lim jarayonining metodologik asosi ekanligi.", "javob": "Ta’lim — insoniyat yaratgan madaniy, ilmiy, axloqiy tajribani yangi avlodga o‘tkazish vositasi. Bilish nazariyasi (gnoseologiya) — inson qanday bilim olishini tushuntiradi. Demak, ta’lim jarayoni bilish nazariyasiga tayangan holda tashkil etiladi: idrok → tushunish → tahlil → umumlashtirish → qo‘llash."},
    {"mavzu": "Pedagogika", "savol": "Ta’limda audiovizual va kompyuter vositalari.", "javob": "Audiovizual vositalar: radio, video, slayd, film, proyektor. Kompyuter vositalari: ta’lim dasturlari, simulyatorlar, interfaol platformalar, sun’iy intellekt tizimlari. Ularning afzalliklari: o‘quvchini faol jalb etadi; materialni ko‘rish va eshitish orqali yaxshiroq o‘zlashtirish; masofaviy o‘qitish imkoniyati."},
    {"mavzu": "Pedagogika", "savol": "Ta’limda innovatsion jarayonlar.", "javob": "Innovatsion jarayon — ta’lim tizimiga yangilik kiritish, sinovdan o‘tkazish va amaliyotga joriy etish bosqichlaridan iborat. Turlari: Pedagogik texnologiyalarni yangilash; AKTni joriy etish; Shaxsga yo‘naltirilgan ta’lim; STEM, STEAM yondashuvlari. Innovatsion faoliyat — o‘qituvchining ijodkorligini va dars samaradorligini oshiradi."},
    {"mavzu": "Pedagogika", "savol": "Ta’limda “sub’ekt–sub’ekt” munosabatlarini amalga oshirish muammolari. Ta’lim va o‘quvchilar o‘quv imkoniyatlarining o‘zaro mutanosibligi.", "javob": "“Sub’ekt–sub’ekt” munosabatlari — o‘qituvchi va o‘quvchi o‘zaro teng, faol hamkor sifatida ishtirok etadigan pedagogik muloqot turi. Muammolar: avtoritar yondashuvning ustunligi; o‘quvchi faolligining pastligi; kommunikativ madaniyat yetishmasligi. O‘quv imkoniyatlarining mutanosibligi — o‘quv yuklamasi va o‘quvchining psixofiziologik imkoniyatlari o‘rtasida muvozanatni ta’minlash demakdir."},
    {"mavzu": "Pedagogika", "savol": "Ta’limni va mustaqil ta’limni amalga oshirish muammolari.", "javob": "Muammolar: o‘quvchilarda mustaqil ishlash ko‘nikmasining sustligi; nazorat va baholash mexanizmlarining yetarli emasligi; motivatsiya pastligi; raqamli resurslardan foydalanish imkoniyatining cheklanganligi. Yechim: interfaol metodlar, masofaviy ta’lim, loyiha asosida o‘qitish, refleksiya tizimini kuchaytirish."},
    {"mavzu": "Pedagogika", "savol": "Ta’limning ikki tomonlama va shaxsga yo‘naltirilgan harakatlari. O‘qitish va o‘qish jarayonining yagonaligi.", "javob": "Ta’lim ikki tomonlama jarayon: o‘qituvchi (sub’ekt) va o‘quvchi (sub’ekt) o‘zaro hamkorlikda faoliyat yuritadi. Shaxsga yo‘naltirilgan ta’lim — har bir o‘quvchining ehtiyoji, qobiliyati, rivojlanish sur’atini inobatga oladi. O‘qitish va o‘qish bir-birini to‘ldiradi: biri bilimni uzatadi, ikkinchisi uni qabul qilib, faol o‘zlashtiradi."},
    {"mavzu": "Pedagogika", "savol": "Ta’limning maorifiy-tarbiyaviy va rivojlantiruvchi funksiyalari. Ta’lim jarayonining tuzilishi, maqsadlari va natijalari.", "javob": "Ta’lim funksiyalari: Maorifiy (bilim berish): ilmiy bilim, ko‘nikma va malaka hosil qilish; Tarbiyaviy: axloq, estetik, vatanparvarlik, ijtimoiy qadriyatlarni shakllantirish; Rivojlantiruvchi: fikrlash, ijodkorlik, mustaqil qaror qabul qilishni rivojlantirish. Tuzilishi: maqsad → mazmun → metod → vosita → shakl → natija."},
    {"mavzu": "Pedagogika", "savol": "Ta’limning og‘zaki metodlari, o‘qitishning induktiv va deduktiv metodlari.", "javob": "Og‘zaki metodlar: hikoya, suhbat, ma’ruza, tushuntirish. Induktiv metod: alohida faktlardan umumiy xulosa chiqarish. (Masalan: misollar orqali qoida chiqarish.) Deduktiv metod: umumiy qoidadan alohida holatlarga o‘tish. (Masalan: qoidadan misolga o‘tish.) Ta’limda bu metodlar o‘zaro uyg‘un qo‘llaniladi."},
    {"mavzu": "Pedagogika", "savol": "Ta’limning psixologik qonuniyatlari va amalga oshirish mexanizmlari.", "javob": "Psixologik qonuniyatlar: o‘quv motivatsiyasi o‘zlashtirish sifatiga ta’sir qiladi; idrok va diqqat barqarorligi o‘quv samaradorligini belgilaydi; takrorlash va mashq qilish xotirani mustahkamlaydi; emotsional fon o‘quv faoliyatini faollashtiradi. Mexanizmlar: motivatsion, kognitiv (bilish), emotsional va irodaviy jarayonlarning uyg‘unligi."},
    {"mavzu": "Pedagogika", "savol": "Ta’limning turli: frontal, jamoaviy, guruhli, individual shakllarining o‘ziga xos xususiyatlari va o‘zaro aloqadorligi.", "javob": "Frontal shakl: butun sinf bilan ishlash; samarali, ammo individual yondashuv kam. Jamoaviy shakl: o‘quvchilar bir maqsadda hamkorlikda ishlaydi. Guruhli shakl: kichik guruhlarda o‘zaro yordam, ijodiy fikr almashish. Individual shakl: har bir o‘quvchi bilan alohida ishlash. Bu shakllar o‘zaro bog‘liq bo‘lib, dars jarayonida kombinatsiyalangan holda qo‘llaniladi."},
    {"mavzu": "Pedagogika", "savol": "Telekommunikatsion o‘quv vositalari.", "javob": "Telekommunikatsion vositalar — internet, elektron pochta, videokonferensiya, onlayn platformalar, masofaviy ta’lim tizimlari (Moodle, Zoom, Google Classroom). Ular yordamida: masofadan turib o‘qitish; global hamkorlik; tezkor teskari aloqa; interaktiv ta’lim amalga oshadi."},
    {"mavzu": "Pedagogika", "savol": "Til tajribasini hisobga olish va og‘zaki nutqning ilgarilashi prinsiplari.", "javob": "Til tajribasi — o‘quvchining avvalgi til bilimlari, lug‘at zaxirasi va nutq tajribasidir. Ilgarilash prinsiplari: eshitish va so‘zlash birligiga asoslanish; muloqotga yo‘naltirish; nutq faoliyatining bosqichma-bosqich rivojlanishi; grammatik qoidalarni amaliy nutq orqali o‘zlashtirish."},
    {"mavzu": "Pedagogika", "savol": "To‘garak, fakultativ mashg‘ulotlari va olimpiadalar tashkil qilish.", "javob": "Maqsad: o‘quvchilarning qiziqishlarini rivojlantirish, chuqurlashtirilgan bilim berish. Tashkil etish bosqichlari: Mavzu va yo‘nalishni tanlash; Dastur ishlab chiqish; Reja tuzish; Mashg‘ulotlarni o‘tkazish va tahlil qilish; Olimpiadalar orqali natijani baholash. Bu mashg‘ulotlar iqtidorli o‘quvchilar bilan ishlashning muhim shaklidir."},
    {"mavzu": "Pedagogika", "savol": "Tushuntirish–illyustratsiyalash, muammoli, dasturlashtirilgan va kompyuterli ta’limni amalga oshirish nazariyalari.", "javob": "Tushuntirish–illyustratsiyalash nazariyasi: o‘qituvchi tayyor bilimni izohlaydi, o‘quvchi qabul qiladi. Muammoli ta’lim: o‘quvchi muammoli vaziyatni hal etish orqali yangi bilim oladi. Dasturlashtirilgan ta’lim: o‘quv materiali kichik qismlarga bo‘linadi, har bosqichda nazorat mavjud. Kompyuterli ta’lim: AKT vositalari orqali individual, interaktiv o‘qitish amalga oshiriladi."},
    {"mavzu": "Pedagogika", "savol": "PQ2909-sonli 2017-yil 20-apreldagi “Oliy ta’lim tizimini yanada rivojlantirish choratadbirlari to‘g‘risida” qarorida pedagogika sohasini rivojlantirishga oid vazifalar quyidagicha tasniflangan:", "javob": "oliy ta’lim muassasalarida xalqaro ta’lim standartlari, zamonaviy pedagogik texnologiyalar va o‘quv-uslubiy materiallarni joriy etish. kadrlar tayyorlash mazmunini qayta ko‘rib chiqish, o‘qituvchi-pedagog kadrlar malakasini oshirish, stajirovkalarni kengaytirish. oliy ta’lim muassasalarini axborot-kommunikatsion texnologiyalar bilan jihozlash, elektron ma’lumotlar bazalariga kirishni ta’minlash. Shu tarzda “pedagogika sohasini rivojlantirish” deya pedagogik kadrlar tayyorlash, malaka oshirish, ta’lim uslublarini yangilash, AKTni joriy etish kabi yo‘nalishlar belgilangan."},
    {"mavzu": "Pedagogika", "savol": "PF60-sonli 2022-yil 28-yanvardagi “20222026yillarga mo‘ljallangan Yangi O‘zbekistonning Taraqqiyot Strategiyasi”da uzluksiz ta’lim tizimini takomillashtirishga oid vazifalar", "javob": "“Inson qadrini yuksaltirish va erkin fuqarolik jamiyatini yanada rivojlantirish” yo‘nalishi doirasida uzluksiz (lifelong) ta’lim tamoyili asosida ta’lim tizimini shakllantirish nazarda tutilgan. yoshlar, maktabdan boshlab, kasbiy va oliy ta’lim bosqichlari orqali hayot davomida o‘qishni davom ettirish imkoniyatlarini kengaytirish. axborot-kommunikatsion texnologiyalarni keng qo‘llash, innovatsiyalarni joriy etish va ta’lim sohasida raqamli transformatsiyani kuchaytirish. Shu bilan birga, uzluksiz ta’lim — shaxsning turli bosqichlardagi ta’lim jarayonlarini uzviy bog‘lash, bilim-ko‘nikmalarni yangilab borish imkoniyatini ta’minlovchi tizim sifatida qaralgan."},
    {"mavzu": "Pedagogika", "savol": "“Uzluksiz ta’limning turli bosqichlari uchun o‘quv-metodik adabiyotlar majmuasini yaratishning pedagogik asoslari” degan qonuniyatli masala:", "javob": "har bir ta’lim bosqichi (maktabgacha, maktab, kollej, oliy, qayta tayyorlash) uchun alohida metodik qo‘llanmalar, darsliklar, masofaviy ta’lim resurslari ishlab chiqilishi pedagogik jihatdan zarur. bu resurslar bir-biriga ulanib borishi, uzluksizlikni ta’minlashi kerak — o‘zaro integratsiya, darajalararo mantiqiy bog‘lanish muhim. ta’lim mazmuni, metodika va vositalar pedagogik qonuniyatlarga (masalan yosh psixologiyasi, faollik tamoyili, differensiallash) asoslanib shakllanishi lozim. Shu tarzda, o‘quv-metodik majmua uzluksiz ta’lim zanjirini pedagogik jihatdan qo‘llab-quvvatlaydi."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitish metodlari va ularni guruhlashtirishning nazariy va metodologik asoslari” —", "javob": "Metod — o‘qitish jarayonida o‘qituvchi va o‘quvchi faoliyatini tashkil etish usuli. (Didaktik asos) Nazariy asoslar: o‘qitish nazariyalari (masalan Galperin, Vygotskiy, Davydov) va metodologik tamoyillar (ilmiylik, tizimlilik, faollik) asosida metodlarni tanlash. Metodlarni guruhlashtirish mezonlari: maqsad, faoliyat turi, vosita, bog‘lanish shakli (masalan og‘zaki, ko‘rgazmali, amaliy), faollik darajasi (reproduktiv, muammoli, tadqiqotli). Shu orqali o‘qitish metodikasi tizimli tarzda tashkil etiladi."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitish natijasini baholash psixologiyasi” — ta’lim jarayonidagi baholash bilan bog‘liq psixologik jihatlar:", "javob": "baholash motivatsiya, o‘quvchi o‘zini baholash hissi, e’tibor va ishtirokini shakllantiradi; baholash turlari (test, og‘zaki, amaliy) psixologik farqlarga ega — stress, adolatlilik, refleksiya imkoniyatlarini hisobga oladi; baholash natijasida o‘quvchi taraqqiyotini ko‘radi, o‘zgarish uchun fikr oladi — bu psixologik o‘zini rivojlantirish jarayonidir."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitishda o‘quvchini rag‘batlantirish metodlari” —", "javob": "ichki rag‘batlantirish: o‘quvchining o‘z ichki motiviga (qiziqish, samaralilik hisi) ta’sir qilish; tashqi rag‘batlantirish: mukofot, yutuq, baho, tan olinish; guruhli rag‘batlantirish: jamoaviy ish, o‘zaro hurmat, ijobiy muhit yaratilishi; differensial rag‘batlantirish: har bir o‘quvchining ehtiyoji va imkoniyatiga mos shaklda rag‘bat berish."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitishni va uning natijalarini nazorat qilish metodlari” —", "javob": "nazorat turlari: dastlabki (diagnostik), joriy, oraliq, yakuniy; metodlari: test sinovlari, yozma ishlar, amaliy topshiriqlar, kompyuter testlari; nazorat natijalari o‘qitish sifatini baholash, xatolarni aniqlash, keyingi bosqichga rejani belgilash uchun asos tashkil qiladi."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitishni tashkil etish shakllari: dialogli, guruhli va ommaviy (frontal)” — har birining xususiyatlari:", "javob": "Dialogli: o‘qituvchi-o‘quvchi o‘zaro muloqotda bo‘ladi, savol-javob, muhokama; Guruhli: kichik guruhlar bilan o‘zaro faoliyat, muammolarni birgalikda yechish; Ommaviy (frontal): butun sinf bilan ishlash, o‘qituvchi markazda; Ushbu shakllar bir darsda kombinatsiyalanishi mumkin — masalan, frontal boshlanadi, so‘ng guruhga bo‘linadi, oxirida dialogli muhokama."},
    {"mavzu": "Pedagogika", "savol": "“O‘qitishni tashkil etishning boshqa shakllari: praktikumlar, seminarlar va fakultativlar” —", "javob": "Praktikumlar: amaliy topshiriqlar, laboratoriya ishlari, kasbiy kompetensiyalarni shakllantirish; Seminarlar: muhokama, tadqiqot ishlarini taqdim etish, o‘quvchilarning faol ishtirokiga asoslangan; Fakultativlar: qo‘shimcha mashg‘ulotlar, ixtisoslashgan yo‘nalishlar, qiziqish asosida; Bu shakllar darsdan tashqari faoliyatni boyitadi, chuqurlashtiradi va individual ehtiyojlarga moslashadi."},
    {"mavzu": "Pedagogika", "savol": "“O‘qituvchi va o‘quvchi faoliyatini, o‘qitish natijalarini baholashda xolislik va ‘formalizm’ga yo‘l qo‘lmaslik shart-sharoitlari. Psixologik-pedagogik diagnostikaning asosiy muammolari.” —", "javob": "Baholash tizimida xolislik — baho adolatli, shaffof, baholash mezonlari aniq bo‘lishi; formalizmga yo‘l qo‘ymaslik — faqat raqam uchun baho qo‘yish emas, o‘quvchining real rivojlanishini ko‘rish. Psixologik-pedagogik diagnostika muammolari: o‘quvchi ehtiyojlari va qobiliyatlarini noto‘liq aniqlash; diagnostika vositalarining yetishmasligi; motivatsiya va emosional holatni inobatga olmaslik; natijalarni faqat baho bilan o‘lchash. — Shu sababli baholash va diagnostika jarayonida metodik to‘liq va psixologik jihatdan sezgir yondashuv zarur."},
    {"mavzu": "Pedagogika", "savol": "O‘qituvchi rahbar va tarbiyachi sifatida", "javob": "O‘qituvchi faqat bilim beruvchi emas, balki shaxs shakllanishiga yo‘naltirilgan rahbar va tarbiyachidir. Uning vazifalari: o‘quvchilar jamoasini boshqarish va yo‘naltirish; axloqiy, estetik, mehnat va jismoniy tarbiyani uyg‘un olib borish; o‘quvchilarda mustaqillik, mas’uliyat va fuqarolik pozitsiyasini shakllantirish. Rahbarlikning pedagogik mohiyati — tarbiyaviy jarayonni boshqarish orqali shaxsning barkamol rivojiga erishishdir."},
    {"mavzu": "Pedagogika", "savol": "O‘qituvchi ta’lim jarayonining sub’ekti ekanligi", "javob": "O‘qituvchi — ta’lim jarayonining asosiy faol ishtirokchisi (sub’ekti) bo‘lib, ta’limning maqsadi, mazmuni, shakli va metodlarini belgilaydi. U nafaqat bilim beruvchi, balki tadqiqotchi, tashabbuskor, tashkilotchi va kommunikator sifatida ham faoliyat yuritadi. Sub’ektivlik — o‘qituvchining ijodiy yondashuvi, pedagogik refleksiyasi va talabalarning shaxsiy rivojiga ta’sir ko‘rsatish qobiliyatida namoyon bo‘ladi."},
    {"mavzu": "Pedagogika", "savol": "O‘quvchilar bilimi, ko‘nikma va malakalarini tekshirish va baholash", "javob": "Nazorat va baholash quyidagi shakllarda amalga oshiriladi: Nazorat ishlari – o‘zlashtirish darajasini aniqlash uchun yozma topshiriqlar; Mustaqil ishlar – bilimni mustaqil qo‘llashni o‘lchaydi; Uy vazifalari – mustahkamlash va ijodiy fikrlashni rivojlantiradi; Test sinovlari – tezkor va obyektiv baholash usuli. Baholashning asosiy maqsadi – o‘quvchining o‘sishini aniqlash, rag‘batlantirish va kamchiliklarni bartaraf etish."},
    {"mavzu": "Pedagogika", "savol": "O‘quvchilar bilish faoliyatini tashkil etish yo‘llari", "javob": "Bilish faoliyati – o‘quvchining o‘rganishga bo‘lgan faol kognitiv jarayoni. Uni tashkil etish yo‘llari: muammoli vaziyatlar yaratish; savol-javob, tadqiqot, eksperiment metodlaridan foydalanish; guruhli va interfaol o‘qitish shakllarini joriy etish; refleksiya va tahlil mashg‘ulotlarini o‘tkazish. Maqsad – o‘quvchini bilimni tayyor emas, balki mustaqil izlab topuvchi sub’ektga aylantirish."},
    {"mavzu": "Pedagogika", "savol": "O‘quvchilar o‘quv faoliyatining motivatsiyasi", "javob": "Motivatsiya – o‘quv faoliyatini harakatga keltiruvchi ichki va tashqi omillar majmui. Turlari: Ichki motivlar – qiziqish, bilishga ehtiyoj, shaxsiy maqsadlar; Tashqi motivlar – baho, mukofot, raqobat, ota-ona va o‘qituvchi talablari. Pedagogik vazifa – o‘quvchining ichki motivini kuchaytirish, tashqi motivni esa qo‘llab-quvvatlash."},
    {"mavzu": "Pedagogika", "savol": "O‘quvchilarning uy vazifasi bajarishlarini tashkil etish muammolari", "javob": "Asosiy muammolar: ortiqcha hajm va murakkablik; uy sharoitining yetarli emasligi; mustaqil ishlash ko‘nikmasining sustligi; nazorat va teskari aloqaning yetishmasligi. Yechim: individual yondashuv, moslashtirgan topshiriqlar, onlayn platformalardan foydalanish, ota-ona bilan hamkorlikni kuchaytirish."},
    {"mavzu": "Pedagogika", "savol": "O‘lchash va mantiqiy metodlar", "javob": "O‘lchash – bilim, ko‘nikma, faoliyat yoki sifatni miqdoriy ifodalash jarayoni. Mantiqiy metodlar: Taqqoslash va analogiya – o‘xshashlik asosida xulosa chiqarish; Umumlashtirish va abstraksiyalash – umumiy qonuniyatni ajratish; Konkretlashtirish – umumiy qoidani konkret holatga tatbiq etish; Induksiya – yakka holatlardan umumiy xulosa; Deduksiya – umumiy qoidani xususiy holga qo‘llash; Analiz va sintez – tahlil va qayta birlashtirish jarayonlari."},
    {"mavzu": "Pedagogika", "savol": "Umummadaniyatni va tajribani egallashni ta’minlovchi ko‘nikma va malakalar tizimi", "javob": "Bu tizim – insonning ijtimoiy, aqliy va amaliy faoliyatini shakllantiruvchi universal kompetensiyalar majmuasi: Intellektual ko‘nikmalar: tanqidiy fikrlash, tahlil, muloqot, axborotni qayta ishlash; Amaliy ko‘nikmalar: kasbiy mahorat, texnik savodxonlik, ijodkorlik; Madaniy ko‘nikmalar: axloq, estetik did, milliy qadriyatlarga sodiqlik. Bu tizim umuminsoniy tajribani avloddan-avlodga o‘tkazishning asosidir."},
    {"mavzu": "Pedagogika", "savol": "Fan bo‘yicha DTS talablari asosida o‘quv-metodik majmualarni takomillashtirishning ilmiy-pedagogik asoslari", "javob": "Ilmiy-pedagogik asoslar: **Davlat ta’lim standarti (DTS)**da belgilangan kompetensiyalarni o‘quv-metodik majmualarda to‘liq aks ettirish; metodik qo‘llanmalarni ilmiylik, izchillik va amaliy yo‘naltirilganlik tamoyillariga asoslash; o‘quv materiallarini yangilash, interfaol texnologiyalarni kiritish; fanlararo integratsiyani ta’minlash."},
    {"mavzu": "Pedagogika", "savol": "Fan bo‘yicha laboratoriya, amaliy va seminar mashg‘ulotlarning maqsadi, vazifalari, ta’lim-tarbiya jarayonida tutgan o‘rni", "javob": "Laboratoriya mashg‘ulotlari – tajriba, o‘lchash, modellashtirish orqali nazariy bilimni amalda qo‘llash. Amaliy mashg‘ulotlar – ko‘nikma hosil qilish, kasbiy tayyorgarlikni mustahkamlash. Seminar mashg‘ulotlari – o‘quvchilarning ilmiy-tadqiqot faoliyatini, nutq va fikrlash madaniyatini rivojlantiradi. Ular ta’lim-tarbiya jarayonida nazariya va amaliyot birligining asosiy shakllaridir."},
    {"mavzu": "Pedagogika", "savol": "Fan bo‘yicha o‘qituvchilarning malakasini oshirish va amaliy-metodik bilimlarini uzluksiz takomillashtirib borish muammolari", "javob": "Muammolar: zamonaviy texnologiyalarni bilmaslik; metodik yangiliklardan xabardorlikning pastligi; malaka oshirish kurslarining amaliy yo‘naltirilmaganligi. Yechimlar: onlayn va oflayn qayta tayyorlash tizimini kuchaytirish; mentorlik va ustoz-shogird tizimini rivojlantirish; fan yangiliklarini o‘rganish uchun doimiy seminar va vebinarlarni yo‘lga qo‘yish."},
    {"mavzu": "Pedagogika", "savol": "Fan ta’limida didaktik tamoyillarni amalga oshirish", "javob": "Asosiy didaktik tamoyillar: Ilmiylik – fan yutuqlariga tayanish; Tizimlilik va izchillik – materialni bosqichma-bosqich o‘rganish; Faollik va mustaqillik – o‘quvchi faol ishtirokini ta’minlash; Nazariya va amaliyot birligi; Ko‘rgazmalilik va tushunarlilik; Individual yondashuv. Ularni amalga oshirish ta’lim samaradorligini oshiradi va o‘quvchini faol sub’ektga aylantiradi."},
    {"mavzu": "Pedagogika", "savol": "Fan o‘qitish metodikasi bo‘yicha ilmiy izlanishlarni o‘tkazishning o‘rni, ahamiyati va asosiy vazifalari", "javob": "Ahamiyati: o‘qitish jarayonini takomillashtirish, yangi pedagogik yondashuvlarni ishlab chiqish. Asosiy vazifalar: o‘qitish metodlarini tajriba asosida tahlil qilish; ilg‘or pedagogik tajribalarni umumlashtirish; o‘quv jarayonida innovatsion yondashuvlarni sinovdan o‘tkazish; ta’lim samaradorligini ilmiy asosda o‘lchash."},
    {"mavzu": "Pedagogika", "savol": "Fan xonasi. Sinfdan tashqari ishlar va ularning asosiy funksiyalari", "javob": "Fan xonasi – o‘quvchilarda fan bo‘yicha mustaqil ishlash, tajriba o‘tkazish va ko‘nikma hosil qilish muhitidir. Sinfdan tashqari ishlar: to‘garaklar, olimpiadalar, fan haftaliklari, loyihalar. Asosiy funksiyalari: qiziqish va ijodkorlikni rivojlantirish; fan yutuqlarini amaliyot bilan bog‘lash; iqtidorli o‘quvchilarni aniqlash va qo‘llab-quvvatlash."},
    {"mavzu": "Pedagogika", "savol": "Fanda uzviylik va uzluksizlik masalalari", "javob": "Uzviylik – fanning turli bosqichlari o‘rtasida mavzu, mazmun va metod jihatidan bog‘liqlikni anglatadi. Uzluksizlik – ta’limning har bir bosqichida (maktab, litsey, oliy ta’lim) bilimlarning tizimli davom etishidir. Bu tamoyillar ta’limda izchillikni, o‘quvchilarning o‘zlashtirish barqarorligini ta’minlaydi."},
    {"mavzu": "Pedagogika", "savol": "Fanni o‘qitish metodikasining predmeti", "javob": "Predmet – o‘quv fanini o‘qitish jarayonida ta’lim mazmuni, shakllari, metodlari va vositalarini o‘rganadigan soha. Ya’ni, bu metodika “nimani, qanday, nima uchun va kimga o‘qitish kerak” degan savollarga javob beradi."},
    {"mavzu": "Pedagogika", "savol": "Fanni o‘qitish metodikasining tadqiqot usullari va ularning nazariy hamda metodologik asoslari", "javob": "Asosiy tadqiqot usullari: Pedagogik kuzatish, so‘rov, tajriba-sinov, taqqoslash, statistik tahlil; Model yaratish va eksperiment; Nazariy tahlil – fan asoslari, qonuniyatlari va didaktik tizimlarni o‘rganish. Metodologik asos – pedagogika, psixologiya, didaktika va falsafa fanlari."},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitish metodikasining tarkibiy qismlari", "javob": "Didaktik qism – o‘quv jarayonining qonuniyatlari; Metodik qism – o‘qitish shakl va usullari; Tashkiliy qism – dars, seminar, laboratoriya jarayonlarini tashkil etish; Baholash qismi – nazorat va teskari aloqa tizimi. Bu qismlar birgalikda fan o‘qitishning to‘liq modelini yaratadi"},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda asosiy vositalar", "javob": "Asosiy o‘quv vositalari: Darslik va qo‘llanmalar – nazariy manba; Didaktik materiallar – testlar, kartochkalar, jadval, sxema; Texnik vositalar – kompyuter, proyektor, sensor doska; Modellar va maketlar – vizual tushunchani shakllantirish. Ularning maqsadi — bilimni tushunarli, ko‘rgazmali va mustahkam qilish."},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda axborot-kommunikatsiya va pedagogik texnologiyalardan uzviy foydalanish", "javob": "Bu – zamonaviy ta’limning eng muhim talabi. AKT vositalari (multimedia, elektron darsliklar, interaktiv platformalar) o‘qitish jarayonini: interfaol, ijodiy va shaxsga yo‘naltirilgan qiladi; vaqtni tejaydi, teskari aloqani tezlashtiradi; o‘quvchini mustaqil o‘rganishga undaydi. Pedagogik texnologiyalar (modulli, muammoli, loyihaviy) esa jarayonni tizimli va natijaviy qiladi"},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda barkamol shaxsni voyaga yetkazish muammolari", "javob": "Barkamol shaxsni shakllantirishda asosiy muammo — ta’lim mazmunining hayotiylikdan uzilib qolishi, o‘quvchi shaxsiga individual yondashuv yetishmasligidir. O‘qituvchi fanni o‘qitishda bilim bilan birga ma’naviy-axloqiy qadriyatlarni singdirish, ijodkorlik va mustaqillikni rivojlantirishga yo‘naltirishi lozim"},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda o‘quv munozaralari va Keys texnologiyasidan foydalanish orqali ularda mantiqiy fikrlash ko‘nikmalarini rivojlantirish", "javob": "O‘quv munozaralari va Keys texnologiyasi (muammoli vaziyatlar tahlili) o‘quvchilarni tahliliy fikrlash, dalillash va xulosa chiqarish faoliyatiga jalb etadi. Bu metodlar orqali o‘quvchi nafaqat faktlarni yodlaydi, balki ularni mantiqan tahlil qilib, hayotiy vaziyatlarda qo‘llashni o‘rganadi."},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda o‘quvchi shaxsiga yo‘naltirilgan va rivojlantiruvchi ta’lim texnologiyalaridan foydalanish orqali yuksak ma’naviyatli barkamol shaxsni voyaga yetkazish yo‘llari", "javob": "Shaxsga yo‘naltirilgan ta’limda o‘quvchi bilim sub’ekti sifatida qaraladi, uning qiziqishlari va ehtiyojlari inobatga olinadi. Rivojlantiruvchi ta’lim texnologiyalari o‘quvchining tafakkurini, axloqiy fazilatlarini va ijtimoiy faolligini rivojlantiradi. Natijada yuksak ma’naviyatli, mustaqil fikrlovchi shaxs shakllanadi."},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda o‘quvchilarda mustaqil, ijodiy, tahliliy va tanqidiy fikr yuritish ko‘nikmalarini tarkib toptirish", "javob": "Bu ko‘nikmalarni shakllantirish uchun muammoli ta’lim, Keys, loyiha, “aql hujumi” va evristik savol-javob metodlaridan foydalaniladi. O‘qituvchi o‘quvchini tayyor javoblarga emas, balki mustaqil izlanish va tahlil orqali xulosa chiqarishga yo‘naltiradi."},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishning maxsus prinsiplari. Didaktik prinsiplarning fanni o‘qitish metodikasiga tatbiq etish xususiyatlari", "javob": "Maxsus prinsiplar — fanga xos qonuniyatlar va o‘qitish usullarini belgilovchi qo‘llanmalar bo‘lib, ular didaktik prinsiplar (onglilik, faollik, tizimlilik, ko‘rgazmalilik, mustahkamlash) bilan uyg‘un holda qo‘llanadi. Har bir fan mazmuni shu prinsiplar asosida metodik yondashuvga ega bo‘ladi."},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitishning metodlari va shakllari. Ularning tasnifi. Umumdidaktik va xususiy predmetli o‘qitish metodlarining o‘zaro aloqadorligi", "javob": "O‘qitish metodlari so‘zli, amaliy, ko‘rgazmali, muammoli va interaktiv turlarga bo‘linadi. Shakllar esa — dars, seminar, laboratoriya, trening va loyiha ishlari. Umumdidaktik metodlar barcha fanlarga xos bo‘lsa, xususiy metodlar muayyan fanning mazmuni va o‘ziga xosligini ifodalaydi"},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishda psixologik prinsiplarining mohiyati", "javob": "Psixologik prinsiplar o‘quvchilarning yosh va individual xususiyatlarini hisobga olib, ta’limni ularning bilish jarayonlariga moslashtirishni talab qiladi. Motivatsiya, idrok, diqqat, xotira va tafakkur jarayonlari o‘qitish samaradorligini belgilaydi"},
 {"mavzu": "Pedagogika", "savol": "Fanni o‘qitishning tashkiliy shakllari", "javob": "Tashkiliy shakllarga dars, seminar, amaliy mashg‘ulot, laboratoriya ishi, konferensiya, to‘garak, ekskursiya va masofaviy ta’lim kiradi. Har bir shakl o‘quvchilarning bilish faoliyatini faollashtirish va amaliy malakalarni rivojlantirishga xizmat qiladi"},
{"mavzu": "Pedagogika", "savol": "Fanni o‘qitishning empirik metodlari: kuzatish, tajriba, o‘lchash", "javob": "Empirik metodlar tajriba yo‘li bilan bilim olishni ta’minlaydi. Kuzatish — hodisani tabiiy sharoitda idrok etish; tajriba (eksperiment) — hodisani maxsus sharoitda o‘rganish; o‘lchash — miqdoriy natijalarni aniqlash orqali xulosaga kelish jarayonidir"},
 {"mavzu": "Pedagogika", "savol": "Oliy ta’limning magistratura bosqichida magistrning o‘zlashtirishi zarur bo‘lgan majburiy ta’lim", "javob": "Magistratura bosqichida majburiy ta’lim — ilmiy-tadqiqot faoliyati, fan metodologiyasi, innovatsion pedagogika, axborot texnologiyalari va xorijiy til bo‘yicha chuqur bilimlarni egallashni nazarda tutadi. Bu bosqichda talaba mustaqil ilmiy izlanish olib borish va ilmiy xulosa chiqarish kompetensiyalarini shakllantiradi"},
  ]

# JSON faylga saqlaymiz
with open('questions.json', 'w', encoding='utf-8') as f:
    json.dump(questions_data, f, ensure_ascii=False, indent=2)

# O'Z TOKENINGIZNI BU YERGA YOZING!!!
API_TOKEN = "8169151448:AAEtH_FneX5rdTE1PeJweGvyXX4aW0rUq3w"

bot = Bot(token=API_TOKEN)
dp = Dispatcher()

with open('questions.json', 'r', encoding='utf-8') as f:
    all_questions = json.load(f)

user_state = {}

def get_menu():
    return InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="Yangi savol", callback_data="new")],
        [InlineKeyboardButton(text="Javobni ko‘rsat", callback_data="answer")]
    ])

@dp.message(Command("start"))
async def start(message: types.Message):
    user_state[message.from_user.id] = {}
    await message.answer(
        "Assalomu alaykum! \nPedagogika imtihon trenažyori\n100 ta savol tayyor!\n\nYangi savol oling:",
        reply_markup=get_menu()
    )

@dp.callback_query(F.data == "new")
async def new_question(query: CallbackQuery):   # <--- bu yerda CallbackQuery


    q = random.choice(all_questions)
    user_state[query.from_user.id] = {"last_q": q}
    savol_raqami = all_questions.index(q) + 1
    await query.message.edit_text(
        f"**Savol {savol_raqami}/100**\n\n{q['savol']}\n\nJavobni ko‘rish uchun tugmani bosing",
        reply_markup=get_menu(),
        parse_mode="Markdown"
    )
    await query.answer()

@dp.callback_query(F.data == "answer")
async def show_answer(query: CallbackQuery):     # <--- bu yerda ham CallbackQuery
    user_id = query.from_user.id
    if user_id not in user_state or "last_q" not in user_state[user_id]:
        await query.answer("Avval yangi savol oling!", show_alert=True)
        return
    javob = user_state[user_id]["last_q"]["javob"]
    await query.message.edit_text(
        f"**Javob:**\n\n{javob}\n\nYana savol olish uchun tugmani bosing",
        reply_markup=get_menu(),
        parse_mode="Markdown"
    )
    await query.answer()

print("100 TA SAVOL TO'LIQ YUKLANDI! Bot ishga tushdi!")
print("Telegramga kiring va /start bosing!")
await dp.start_polling(bot)
